apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webui
  name: webui
  namespace: pretest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  strategy: {}
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - image: dockercoins/webui:v0.1
        name: webui
	ports:
            - containerPort: 8080
              name: webui
        resources: {}
status: {}
