apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hasher
  name: hasher
spec:
  ports:
  - name: hasher
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hasher
  type: ClusterIP
status:
  loadBalancer: {}
