apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasher
  name: hasher
  namespace: pretest
spec:
  ports:
  - name: hasher
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  type: ClusterIP
status:
  loadBalancer: {}
