apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: pretest
spec:
  ports:
  - name: redis
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: redis
  type: ClusterIP
status:
  loadBalancer: {}
