apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rng
  name: rng
  namespace: pretest
spec:
  ports:
  - name: rng
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rng
  type: ClusterIP
status:
  loadBalancer: {}
