apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rng
  name: rng
  namespace: pretest
spec:
  ports:
  - name: rng
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rng
  type: ClusterIP
status:
  loadBalancer: {}
