apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webui
  name: webui
  namespace: pretest
spec:
  ports:
  - name: webui
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  type: ClusterIP
status:
  loadBalancer: {}
