apiVersion: v1
kind: Service
metadata:
  labels:
    app: webui
  name: webui
  namespace: pretest
spec:
  ports:
  - name: 8080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  type: NodePort
status:
  loadBalancer: {}
