apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
  name: worker
  namespace: pretest
spec:
  ports:
  - name: 8080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: worker
  type: ClusterIP
status:
  loadBalancer: {}
