apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  ports:
  - name: worker
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: worker
  type: ClusterIP
status:
  loadBalancer: {}
